In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn import tree
from sklearn.svm import SVC
from sklearn.metrics import mean_squared_error as MSE

In [28]:
csvFile = pd.read_csv('../Datasets/winequality-red.csv')
colNames = list(csvFile.columns)

print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('quality')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['quality'].values

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


In [29]:
# Randomize the data because it could be sorted.
numsMe = np.random.permutation(csvFile.shape[0])
_thresh = int(np.floor(csvFile.shape[0]*.8))

print(numsMe)
print(_thresh)

trainInds =  numsMe[:_thresh]
testInds  =  numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y[trainInds], Y[testInds]

[ 367 1394  652 ...  666 1467 1534]
1279


In [30]:
# clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
# clf.fit(TrainX, TrainY)

clf_dt = tree.DecisionTreeClassifier()
clf_dt = clf_dt.fit(TrainX, TrainY)

clf_nn = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12,), random_state=1)
clf_nn.fit(TrainX, TrainY)

clf_nn_reg = MLPRegressor(solver='adam', alpha=1e-5, hidden_layer_sizes=(12,), random_state=1)
clf_nn_reg.fit(TrainX, TrainY)

clf_svm = SVC()
clf_svm = clf_svm.fit(TrainX, TrainY)

models = [clf_dt, clf_nn, clf_nn_reg, clf_svm]

C:\Users\schul\AppData\Local\pypoetry\Cache\virtualenvs\week_2-fQXySU9Y-py3.10\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\schul\AppData\Local\pypoetry\Cache\virtualenvs\week_2-fQXySU9Y-py3.10\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [33]:
# Results
for i in models:
    print(i)
    preds = i.predict(TestX)
    if type(i) == MLPRegressor:
        mse = MSE(TestY, preds)
        print(mse)
    else:
        # predicted class horizontal, actual class vertical
        cm = confusion_matrix(TestY, preds)
        print(cm)

        # giving the predictions of our model and comparing to our test
        acc = accuracy_score(TestY, preds)
        print(acc)

        # different classes have different quantity of data for training (some are better), so we balance the accuracy between the classes and get a better rating for the whole model
        accb = balanced_accuracy_score(TestY, preds)
        print(accb)

DecisionTreeClassifier()
[[  0   0   0   1   0   0]
 [  1   2   3   3   1   0]
 [  1   9 106  24   3   0]
 [  0   3  25  77  10   1]
 [  0   1   7  18  21   0]
 [  0   0   0   1   2   0]]
0.64375
0.34197672589088585
MLPClassifier(alpha=1e-05, hidden_layer_sizes=(12,), random_state=1)
[[ 0  0  1  0  0  0]
 [ 0  0  2  8  0  0]
 [ 0  0 99 44  0  0]
 [ 0  1 35 79  1  0]
 [ 0  1  5 37  4  0]
 [ 0  0  0  3  0  0]]
0.56875
0.24307475967417272
MLPRegressor(alpha=1e-05, hidden_layer_sizes=(12,), random_state=1)
0.5181013072605832
SVC()
[[ 0  0  0  1  0  0]
 [ 0  0  1  9  0  0]
 [ 0  0 66 77  0  0]
 [ 0  0 24 92  0  0]
 [ 0  0  6 41  0  0]
 [ 0  0  1  2  0  0]]
0.49375
0.20910698496905397
