In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn import tree

In [23]:
csvFile = pd.read_csv('../Datasets/winequality-red.csv')
colNames = list(csvFile.columns)

print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('quality')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['quality'].values

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


In [24]:
# Randomize the data because it could be sorted.
numsMe = np.random.permutation(csvFile.shape[0])
_thresh = int(np.floor(csvFile.shape[0] * .8))

print(numsMe)
print(_thresh)

trainInds = numsMe[:_thresh]
testInds = numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y[trainInds], Y[testInds]

[1430 1467  529 ... 1523  487  937]
1279


In [25]:
# clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
# clf.fit(TrainX, TrainY)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(TrainX, TrainY)


In [26]:
preds = clf.predict(TestX)

# predicted class horizontal, actual class vertical
cm = confusion_matrix(TestY, preds)
print(cm)

# giving the predictions of our model and comparing to our test
acc = accuracy_score(TestY, preds)
print(acc)

# different classes have different quantity of data for training (some are better), so we balance the accuracy between the classes and get a better rating for the whole model
accb = balanced_accuracy_score(TestY, preds)
print(accb)

[[ 0  3  2  0  0  0]
 [ 0  0 12  2  1  0]
 [ 1  7 94 25  3  0]
 [ 0  5 35 79 13  1]
 [ 0  1  3  6 18  4]
 [ 0  0  1  0  3  1]]
0.6
0.34659364758048966


In [27]:
correct_preds = 0
# print(len(preds), len(TestY))
for index, i in enumerate(preds):
    if i == TestY[index]:
        correct_preds = correct_preds + 1
# print("Number Testdata" + str(len(TestY)))
accuracy = correct_preds / len(TestY)
print("Accuracy=" + str(accuracy))

Accuracy=0.6


In [28]:
# Number of true positive
