In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn import tree
from sklearn.svm import SVC

In [50]:
csvFile = pd.read_csv('../Datasets/winequality-red.csv')
colNames = list(csvFile.columns)

print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('quality')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['quality'].values

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


In [51]:
numsMe = np.random.permutation(csvFile.shape[0])
_thresh = int(np.floor(csvFile.shape[0]*.8))

print(numsMe)
print(_thresh)

trainInds =  numsMe[:_thresh]
testInds  =  numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y[trainInds], Y[testInds]

[ 679  591 1456 ... 1551  275 1483]
1279


In [52]:
# clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
# clf.fit(TrainX, TrainY)

# clf = tree.DecisionTreeClassifier()
# clf = clf.fit(TrainX, TrainY)

clf = SVC()
clf = clf.fit(TrainX, TrainY)



In [53]:
preds = clf.predict(TestX)

cm = confusion_matrix(TestY, preds)
print(cm)

acc = accuracy_score(TestY, preds)
print(acc)

accb = balanced_accuracy_score(TestY, preds)
print(accb)

[[  0   2   5   0   0]
 [  0  67  74   0   0]
 [  0  32 101   0   0]
 [  0   5  32   0   0]
 [  0   1   1   0   0]]
0.525
0.24691516024102808
