In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score

In [7]:
csvFile = pd.read_csv('../Datasets/winequality-red.csv')
colNames = list(csvFile.columns)

print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('quality')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['quality'].values

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


In [8]:
numsMe = np.random.permutation(csvFile.shape[0])
_thresh = int(np.floor(csvFile.shape[0]*.8))

print(numsMe)
print(_thresh)

trainInds =  numsMe[:_thresh]
testInds  =  numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y[trainInds], Y[testInds]

[ 110 1088  961 ... 1596 1016 1081]
1279


In [9]:
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
clf.fit(TrainX, TrainY)

C:\Users\schul\AppData\Local\pypoetry\Cache\virtualenvs\week_2-fQXySU9Y-py3.10\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(12,), random_state=1)

In [10]:
preds = clf.predict(TestX)

cm = confusion_matrix(TestY, preds)
print(cm)

acc = accuracy_score(TestY, preds)
print(acc)

accb = balanced_accuracy_score(TestY, preds)
print(accb)

[[ 0  0  0  1  0  0]
 [ 0  0  8  2  0  0]
 [ 0  0 98 37  0  0]
 [ 0  0 40 82  0  0]
 [ 0  0  5 43  0  0]
 [ 0  0  0  4  0  0]]
0.5625
0.23300951224448493
