In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn import tree

In [15]:
csvFile = pd.read_csv('../Datasets/Dataset2.csv')
colNames = list(csvFile.columns)

print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('Y')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['Y'].values

['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'Y']


In [21]:
# Randomize the data because it could be sorted.
numsMe = np.random.permutation(csvFile.shape[0])

# Normalize the data
for i in range(X.shape[1]):
    # Scaling normalization
    X[:, i] = (X[:, i] - np.amin(X[:, i])) / (np.amax(X[:, i]) - np.amin(X[:, i]))

# print(X)
# Split the data into training and testing
_thresh = int(np.floor(csvFile.shape[0] * .8))

# print(numsMe)
# print(_thresh)

trainInds = numsMe[:_thresh]
testInds = numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y[trainInds], Y[testInds]

[[0.54220203 0.53558762 0.58192221 0.38757401 0.50345044 0.32572426]
 [0.5024821  0.66570861 0.60854324 0.6497673  0.15291267 0.25092014]
 [0.65879189 0.47351304 0.69698654 0.4215717  0.62688795 0.4794807 ]
 ...
 [0.58525998 0.52728988 0.48779673 0.53781446 0.47192761 0.39445905]
 [0.59773904 0.26696428 0.50588613 0.18933201 0.86855811 0.61962737]
 [0.61464158 0.53079299 0.47949704 0.61145476 0.54809624 0.38035365]]


In [17]:
# clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
# clf.fit(TrainX, TrainY)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(TrainX, TrainY)


In [18]:
preds = clf.predict(TestX)

# predicted class horizontal, actual class vertical
cm = confusion_matrix(TestY, preds)
print(cm)

# giving the predictions of our model and comparing to our test
acc = accuracy_score(TestY, preds)
print(acc)

# different classes have different quantity of data for training (some are better), so we balance the accuracy between the classes and get a better rating for the whole model
accb = balanced_accuracy_score(TestY, preds)
print(accb)

[[17  3  2  5]
 [ 3 15  8  3]
 [ 2  2 28  4]
 [ 3  9  5 19]]
0.6171875
0.6131066411238825


In [19]:
correct_preds = 0
# print(len(preds), len(TestY))
for index, i in enumerate(preds):
    if i == TestY[index]:
        correct_preds = correct_preds + 1
# print("Number Testdata" + str(len(TestY)))
accuracy = correct_preds / len(TestY)
print("Accuracy=" + str(accuracy))

Accuracy=0.6171875
