In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn import tree

In [3]:
csvFile = pd.read_csv('../Datasets/Dataset2.csv')
colNames = list(csvFile.columns)

# print(colNames)

colNamesX = colNames.copy()
colNamesX.remove('Y')
dfX = csvFile[colNamesX]
X = dfX.values
Y = csvFile['Y'].values

In [4]:
# Randomize the data because it could be sorted.
numsMe = np.random.permutation(csvFile.shape[0])

Y_Arr = np.zeros((Y.shape[0], 3))
for i in range(Y.shape[0]):
    if Y[i] == 1:
        Y_Arr[i] = [1, 0, 0]
    elif Y[i] == 2:
        Y_Arr[i] = [0, 1, 0]
    elif Y[i] == 3:
        Y_Arr[i] = [0, 0, 1]

_thresh = int(np.floor(csvFile.shape[0] * .8))

print(numsMe)
print(_thresh)

trainInds = numsMe[:_thresh]
testInds = numsMe[_thresh:]

TrainX, TestX = X[trainInds], X[testInds]
TrainY, TestY = Y_Arr[trainInds,:], Y_Arr[testInds,:]

# print(TrainY)

[ 84 130 416 225 363  61 337 468  57 340 100  50  41 307  55 361 371 148
 539  48 552   3 605 269 362 177 583 396 186 171 407  52 417 494 138 229
  80  23 154 238 486 199 369 575   2  96 594 464 270 365 628 351  86 248
 164 414 614 376 308 324 259 111 132 428  88 323 599 330 461 304 246 333
 434 483 268 406 476 201  89 412  58 173 472 429  43 422 389 388 265 556
 508  85 450  91 163 114  71 134 170 258 634 353 109 499  37 520 366 223
 352  31 237 451 283  93 563 460 212 165 298 630 623 405 271 570 219 503
 501 409  27  67 612 579 387 470 609 345 456  11 242 482 203 488 142 572
 267  12  60  46  34 204 622 577 146 282  29 123   4 565 221 562 273  73
 535 349 415 596 185  35 377 128 544 105  24   5 571 112  63 141 181 367
 584  56 455 627 515 551  20 280 121 410 449 473 495 518 454 113 507 484
 430 313 147  26 523 537  65 573 232 380 295 245 479 403 381 336 180 266
 208 150 582 372 593 385 522 432 317 315 287 215 178 541 169 188 140 194
 125 261 139 506 214 153 155  78 437 487  81 626 38

In [5]:
# clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(12, ), random_state=1)
# clf.fit(TrainX, TrainY)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(TrainX, TrainY)


In [10]:
preds = clf.predict(TestX)
# print(preds)
# predicted class horizontal, actual class vertical
# cm = confusion_matrix(TestY, preds)
# print(cm)

# giving the predictions of our model and comparing to our test
# acc = accuracy_score(TestY, preds)
# print(acc)

# different classes have different quantity of data for training (some are better), so we balance the accuracy between the classes and get a better rating for the whole model
# accb = balanced_accuracy_score(TestY, preds)
# print(accb)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0.

In [23]:
correct_preds = 0
for index, i in enumerate(preds):
    if np.array_equal(i, TestY[index]):
        correct_preds = correct_preds + 1
accuracy = correct_preds / len(TestY)
print("Accuracy=" + str(accuracy))

Accuracy=0.671875


In [ ]:
# Number of true positive
